# Generated by Django 2.1.2 on 2018-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
