# Generated by Django 2.1.2 on 2018-10-28 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0007_auto_20181026_2117'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='note',
            managers=[
            ],
        ),
    ]
