# Generated by Django 2.1.2 on 2018-11-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0008_auto_20181028_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_code', models.CharField(max_length=4)),
            ],
        ),
    ]
