# Generated by Django 2.1.2 on 2018-11-01 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0009_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='country',
        ),
    ]
