# Generated by Django 2.1.2 on 2018-11-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0010_remove_userinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete='Cascade', to='UserProfile.Country'),
        ),
    ]
